import React, { useState } from 'react';
import { 
  Sparkles, 
  ShieldCheck, 
  Copy, 
  Check, 
  AlertTriangle, 
  MapPin, 
  Clock, 
  FileText, 
  CheckCircle2, 
  Layers, 
  Compass, 
  HelpCircle 
} from 'lucide-react';

export default function BriefingViewer({ rawBriefing }) {
  const [copied, setCopied] = useState(false);

  if (!rawBriefing) return null;

  const handleCopy = () => {
    navigator.clipboard.writeText(rawBriefing);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // Helper to parse and clean markdown into formatted sections
  const formatText = (text) => {
    // Replace markdown symbols and math arrows for clean presentation
    let cleaned = text
      .replace(/\\rightarrow|\$\\rightarrow\$/g, ' → ')
      .replace(/\*\*(.*?)\*\*/g, '$1');
    return cleaned;
  };

  // Simple section splitter
  const lines = rawBriefing.split('\n');
  const sections = [];
  let currentSection = { title: 'Executive Overview', content: [] };

  lines.forEach((line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed === '---') return;

    if (trimmed.startsWith('# ') || trimmed.startsWith('## ') || trimmed.startsWith('### ')) {
      if (currentSection.content.length > 0) {
        sections.push(currentSection);
      }
      currentSection = {
        title: trimmed.replace(/^#+\s*/, '').replace(/\*+/g, ''),
        content: [],
      };
    } else {
      currentSection.content.push(trimmed);
    }
  });
  if (currentSection.content.length > 0) {
    sections.push(currentSection);
  }

  return (
    <div className="bg-slate-900 border border-orange-500/40 rounded-2xl overflow-hidden shadow-xl animate-in fade-in duration-300">
      {/* Header bar */}
      <div className="bg-gradient-to-r from-orange-950/60 via-slate-900 to-slate-900 border-b border-orange-500/20 p-4 sm:p-5 flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center space-x-3">
          <div className="w-10 h-10 rounded-xl bg-orange-500/10 border border-orange-500/30 flex items-center justify-center text-orange-400 font-bold shadow-inner">
            <Sparkles className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-base font-bold text-white tracking-tight flex items-center gap-2">
              Operational Rescue Briefing
            </h3>
            <span className="text-[11px] text-slate-400 flex items-center gap-1">
              <span className="w-2 h-2 rounded-full bg-emerald-400 inline-block animate-pulse"></span>
              Generated by Gemini AI • Structured for Search Coordinators
            </span>
          </div>
        </div>

        <button
          onClick={handleCopy}
          className="px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 border border-slate-700 text-xs font-semibold flex items-center gap-1.5 transition"
        >
          {copied ? (
            <>
              <Check className="w-3.5 h-3.5 text-emerald-400" />
              <span className="text-emerald-400">Copied to Clipboard</span>
            </>
          ) : (
            <>
              <Copy className="w-3.5 h-3.5" />
              <span>Copy Full Briefing</span>
            </>
          )}
        </button>
      </div>

      {/* Safety Alert Banner */}
      <div className="bg-amber-950/40 border-b border-amber-900/40 px-5 py-2.5 text-xs text-amber-200/90 flex items-center space-x-2">
        <AlertTriangle className="w-4 h-4 text-amber-400 flex-shrink-0" />
        <span>
          <strong>Operational Guideline:</strong> All sightings are unconfirmed witness leads prioritized for verification. Never confront subjects directly.
        </span>
      </div>

      {/* Structured Sections Body */}
      <div className="p-6 space-y-6">
        {sections.map((sec, idx) => {
          const isSafety = sec.title.toLowerCase().includes('ai-generated') || sec.title.toLowerCase().includes('verify');
          if (isSafety) return null;

          return (
            <div key={idx} className="space-y-3 bg-slate-800/40 border border-slate-800 p-4 sm:p-5 rounded-xl">
              <h4 className="text-sm font-bold text-orange-400 uppercase tracking-wider flex items-center gap-2 border-b border-slate-750 pb-2">
                <FileText className="w-4 h-4 text-orange-400" />
                {sec.title}
              </h4>

              <div className="space-y-2 text-xs sm:text-sm text-slate-200 leading-relaxed">
                {sec.content.map((p, pIdx) => {
                  const cleaned = formatText(p);

                  // Priority list items
                  if (cleaned.startsWith('* ') || cleaned.startsWith('- ')) {
                    const itemContent = cleaned.replace(/^[\*\-]\s*/, '');
                    return (
                      <div key={pIdx} className="flex items-start space-x-2.5 pl-1 py-0.5">
                        <span className="w-1.5 h-1.5 rounded-full bg-orange-400 mt-2 flex-shrink-0"></span>
                        <span className="text-slate-300">{itemContent}</span>
                      </div>
                    );
                  }

                  // Numbered chronological steps
                  if (/^\d+\.\s/.test(cleaned)) {
                    return (
                      <div key={pIdx} className="bg-slate-900/60 border border-slate-800 p-3 rounded-lg flex items-start space-x-3 my-1.5">
                        <span className="w-6 h-6 rounded-full bg-orange-950 text-orange-300 border border-orange-800 flex items-center justify-center text-xs font-bold flex-shrink-0">
                          {cleaned.match(/^\d+/)[0]}
                        </span>
                        <div className="text-slate-200">
                          {cleaned.replace(/^\d+\.\s*/, '')}
                        </div>
                      </div>
                    );
                  }

                  return (
                    <p key={pIdx} className="text-slate-300 font-normal">
                      {cleaned}
                    </p>
                  );
                })}
              </div>
            </div>
          );
        })}
      </div>

      {/* Official Signoff Footer */}
      <div className="bg-slate-950/80 border-t border-slate-800 p-4 text-center text-xs font-mono text-slate-400 flex items-center justify-center gap-1.5">
        <ShieldCheck className="w-4 h-4 text-emerald-400" />
        <span>AI-generated briefing. Verify information with authorized responders.</span>
      </div>
    </div>
  );
}
